---
- name: "Ensure the appdata directory for services exist"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ docker_container_puid | int }}"
    group: "{{ docker_container_pgid | int }}"
  with_items:
    - "{{ docker_compose_root }}"
    - "{{ nzb_compose_file | dirname }}"
    - "{{ nzb_sabnzbd_config_dir }}"
    - "{{ nzb_sonarr_config_dir }}"
    - "{{ nzb_bazarr_config_dir }}"
    - "{{ nzb_prowlarr_config_dir }}"
    - "{{ nzb_lidarr_config_dir }}"
    - "{{ nzb_searcharr_root_dir }}"

- name: Ensure the docker-compose file is present
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ nzb_compose_file }}"

- name: Ensure the beets import script is present
  ansible.builtin.template:
    src: beets-import
    dest: "{{ nzb_sabnzbd_scripts_dir }}/beets-import"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "744"

- name: Ensure searcharr config is present
  template:
    src: settings.py
    dest: "{{ nzb_searcharr_root_dir }}/settings.py"

- name: "Ensure the {{ service_name }} stack is running"
  community.docker.docker_compose_v2:
    project_name: "{{ service_name }}"
    project_src: "{{ nzb_compose_file | dirname }}"
  vars:
    ansible_python_interpreter: "{{ ansible_docker_venv_bin }}"
