---
service_name: nzb

nzb_compose_file: "{{ docker_compose_root }}/{{ service_name }}/docker-compose.yml"

nzb_data_root:

nzb_sabnzbd_config_dir: "{{ docker_container_data_root }}/sabnzbd"
nzb_sabnzbd_scripts_dir: "{{ nzb_sabnzbd_config_dir }}/scripts"

nzb_sonarr_config_dir: "{{ docker_container_data_root }}/sonarr"

nzb_radarr_config_dir: "{{ docker_container_data_root }}/radarr"

nzb_bazarr_config_dir: "{{ docker_container_data_root }}/bazarr"

nzb_lidarr_config_dir: "{{ docker_container_data_root }}/lidarr"

nzb_prowlarr_config_dir: "{{ docker_container_data_root }}/prowlarr"

nzb_searcharr_root_dir: "{{ docker_container_data_root }}/searcharr"
nzb_searcharr_data_dir: "{{ nzb_searcharr_root_dir }}/data"
nzb_searcharr_logs_dir: "{{ nzb_searcharr_root_dir }}/logs"
